const fs = require("fs");
const PDFDocument = require("pdfkit");
const path = require("path");

function generateEstimatePDF(estimate) {
    return new Promise((resolve, reject) => {
        try {
            const pdfDir = path.join(__dirname, "..", "..", "pdfs");
            const pdfPath = path.join(pdfDir, `estimate_${estimate._id}.pdf`);

            const doc = new PDFDocument();
            const writeStream = fs.createWriteStream(pdfPath);
            doc.pipe(writeStream);

            // Title
            doc.fontSize(20).text("HVAC Service Estimate", { align: "center" });
            doc.moveDown();

            // General Info
            doc.fontSize(12).text(`Estimate ID: ${estimate._id}`);
            doc.text(`Date: ${new Date().toLocaleDateString()}`);
            doc.moveDown();

            // Customer Information
            doc.font("Helvetica-Bold").text("Customer Information:", { underline: true });
            doc.font("Helvetica").text(`Name: ${estimate.customerName}`);
            doc.text(`Phone: ${estimate.customerPhone}`);
            doc.text(`Email: ${estimate.customerEmail}`);
            doc.text(`Location: ${estimate.customerLocation}`);
            doc.moveDown();

            // Service Details
            doc.font("Helvetica-Bold").text("Service Details:", { underline: true });
            doc.font("Helvetica").text(`Service Type: ${estimate.serviceType}`);
            doc.text(`Unit Number: ${estimate.unitNumber}`);
            doc.text(`Model Number: ${estimate.modelNumber}`);
            doc.text(`Labor Hours: ${estimate.laborHours}`);
            doc.moveDown();

            // Issue Description
            doc.font("Helvetica-Bold").text("Issue Description:", { underline: true });
            doc.font("Helvetica").text(estimate.issue || "N/A", { indent: 20 });
            doc.moveDown();

            // Footer
            doc.font("Helvetica-Oblique")
                .fontSize(10)
                .text("Generated by HVAC Estimate System", { align: "center" });

            doc.end();

            writeStream.on("finish", () => {
                console.log(`PDF generated at ${pdfPath}`);
                resolve(`/pdfs/estimate_${estimate._id}.pdf`);
            });

            writeStream.on("error", (err) => {
                console.error("Error writing PDF:", err);
                reject(err);
            });
        } catch (error) {
            reject(error);
        }
    });
}

module.exports = generateEstimatePDF;